version: "1.0"

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "cloud-search-backend:latest"

build_backend:
  stage: build
  script:
    - echo "Building backend image..."
    - docker build -t $IMAGE_NAME .

deploy_backend:
  stage: deploy
  script:
    - echo "Restart backend container..."
    - docker compose -f /home/ubuntu/cloud-search-app/docker-compose.yml up -d backend
  when: on_success
